# config/packages/security.yaml

security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Participant # Modifié pour utiliser Participant
                property: email # Ou 'username' si vous utilisez le pseudo pour la connexion

    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: home
                username_parameter: _username
                password_parameter: _password
            logout:
                path: logout

    access_control:
         - { path: ^/login }
         - { path: ^/register }
         - { path: ^/home, roles: ROLE_USER } # Seuls les utilisateurs connectés peuvent accéder à /home
         - { path: ^/, roles: ROLE_USER } # Par défaut, toutes les autres routes sont protégées
