security:
    # Configuration des password hashers
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Fournisseurs d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Participant
                property: email  # On garde la propriété email ici car tu gères login/pseudo dans l'authentificateur

    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: home
                username_parameter: _login  # Utilisation d'un paramètre générique pour login (email ou pseudo)
                password_parameter: _password
            logout:
                path: logout
                target: login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: false
            http_basic:  # Ajout de HTTP Basic
                realm: "Secured Area"
            # Spécification de l'entry point pour éviter le conflit
            # Désactiver HTTP Basic si tu n'en as pas besoin
            # http_basic:
            #     realm: "Secured Area"
            # Spécification de l'entry point pour éviter le conflit
            entry_point: form_login  # Garder form_login comme entry point principal
    access_control:
        - { path: ^/login }
        - { path: ^/register }
        - { path: ^/reset-password }
        - { path: ^/home, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api/sorties, roles: ROLE_USER }
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/, roles: ROLE_USER }
